### ISSUE TITLE
Accessibility Testing

### ISSUE THREAD

**Issue by camelPhonso** [fac27/ZanyMen#20]

**Comment by camelPhonso** [comment]
@zakkariyaa I was having a test with the screen reader today and we'll need to figure out a way for it to be clear when users need to select one of the two forms. I think I can sort that out with aria properties and tabIndex but it highlighted another thing:

The buttons on the header should be actual buttons instead of paragraphs. I tried changing this but the classes on CSS seem to be overlapping so my edits weren't coming through very well. Could you make that change please?

**Comment by camelPhonso** [comment]
@zakkariyaa I was having a test with the screen reader today and we'll need to figure out a way for it to be clear when users need to select one of the two forms. I think I can sort that out with aria properties and tabIndex but it highlighted another thing:

The buttons on the header should be actual buttons instead of paragraphs. I tried changing this but the classes on CSS seem to be overlapping so my edits weren't coming through very well. Could you make that change please?

**Comment by zakkariyaa** [comment]
@camelPhonso I have made the changes. Please check last pr

**Comment by zakkariyaa** [comment]
@camelPhonso i have also noticed a horizontal scrollbar appears at the bottom of the page. Can you look into that?
